apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: ccp-istio-operator
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      serviceAccountName: ccp-istio-operator
      containers:
      - name: ccp-istio-operator
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: chart-volume
          mountPath: {{ .Values.chartsPath }}
        env:
          - name: CHARTS_PATH
            value: {{ .Values.chartsPath }}
      volumes:
      - name: chart-volume
        hostPath:
          path: {{ .Values.chartsPath }}
          type: Directory
