# CR to deploy istio 1.1.8

apiVersion: operator.ccp.cisco.com/v1alpha1
kind: Istio
metadata:
  name: ccp-istio
spec:
  # istio-init
  istio-init:
    chart: /opt/ccp/charts/istio-init-1.1.8-ccp1.tgz
    values: |-
      global:
        hub: registry.ci.ciscolabs.com/cpsg_ccp-docker-istio
        tag: 1.1.8-ccp1
        imagePullPolicy: IfNotPresent
      certmanager:
        enabled: false
  # istio
  istio:
    chart: /opt/ccp/charts/istio-1.1.8-ccp1.tgz
    values: |-
      gateways:
        istio-egressgateway:
          enabled: true
        enabled: true
      sidecarInjectorWebhook:
        enabled: true
      galley:
        enabled: true
      mixer:
        enabled: true
        policy:
          enabled: true
        telemetry:
          enabled: true
      pilot:
        enabled: true
      security:
        enabled: true
      nodeagent:
        enabled: false
      grafana:
        enabled: true
        image:
          repository: registry.ci.ciscolabs.com/cpsg_ccp-charts/grafana/grafana
          tag: 6.0.0
        global:
          imagePullPolicy: IfNotPresent
      prometheus:
        enabled: true
        hub: registry.ci.ciscolabs.com/cpsg_ccp-charts/prom
        tag: v2.7.1
      servicegraph:
        enabled: false
      tracing:
        enabled: false
      kiali:
        enabled: false
      istio_cni:
        enabled: false
      istiocoredns:
        enabled: false
      global:
        hub: registry.ci.ciscolabs.com/cpsg_ccp-docker-istio
        tag: 1.1.8-ccp1
        logging:
          level: "default:info"
        monitoringPort: 15014
        k8sIngress:
          enabled: false
          gatewayName: ingressgateway
          enableHttps: false
        proxy:
          image: proxyv2
          clusterDomain: "cluster.local"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 128Mi
          concurrency: 2
          accessLogFile: ""
          accessLogFormat: ""
          accessLogEncoding: TEXT
          logLevel: ""
          dnsRefreshRate: 5s
          privileged: false
          enableCoreDump: false
          statusPort: 15020
          readinessInitialDelaySeconds: 1
          readinessPeriodSeconds: 2
          readinessFailureThreshold: 30
          includeIPRanges: "*"
          excludeIPRanges: ""
          kubevirtInterfaces: ""
          includeInboundPorts: "*"
          excludeInboundPorts: ""
          autoInject: enabled
          envoyStatsd:
            enabled: false
            host: # example: statsd-svc.istio-system
            port: # example: 9125
          envoyMetricsService:
            enabled: false
            host: # example: metrics-service.istio-system
            port: # example: 15000
          tracer: "zipkin"
        proxy_init:
          image: proxy_init
        imagePullPolicy: IfNotPresent
        controlPlaneSecurityEnabled: false
        disablePolicyChecks: true
        policyCheckFailOpen: false
        enableTracing: true
        tracer:
          lightstep:
            address: ""                # example: lightstep-satellite:443
            accessToken: ""            # example: abcdefg1234567
            secure: true               # example: true|false
            cacertPath: ""             # example: /etc/lightstep/cacert.pem
          zipkin:
            address: ""
          datadog:
            address: "$(HOST_IP):8126"
        mtls:
          enabled: false
        imagePullSecrets:
        arch:
          amd64: 2
          s390x: 2
          ppc64le: 2
        oneNamespace: false
        defaultNodeSelector: {}
        configValidation: true
        meshExpansion:
          enabled: false
          useILB: false
        multiCluster:
          enabled: false
        defaultResources:
          requests:
            cpu: 10m
        defaultPodDisruptionBudget:
          # disable defaultPodDisruptionBudget as it fails upgrade test in CCP CI when
          # evicting istio pods during tenant upgrade
          enabled: false
        priorityClassName: ""
        useMCP: true
        trustDomain: ""
        outboundTrafficPolicy:
          mode: ALLOW_ANY
        sds:
          enabled: false
          udsPath: ""
          useTrustworthyJwt: false
          useNormalJwt: false
        meshNetworks: {}
        localityLbSetting: {}
        enableHelmTest: false
  # istio-remote
  istio-remote:
    chart: ""
    values: ""
