
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.ccp.cisco.com
  resources:
  - istios
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - operator.ccp.cisco.com
  resources:
  - istios/status
  verbs:
  - get
  - update
  - patch
