apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: ccp-istio-operator
  namespace: default
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      serviceAccountName: ccp-istio-operator
      containers:
      - name: ccp-istio-operator
        image: ccp-istio-operator:ffeecb0
        imagePullPolicy: Always
        volumeMounts:
        - name: chart-volume
          mountPath: /opt/ccp/charts/
        env:
          - name: CHARTS_PATH
            value: /opt/ccp/charts/
      volumes:
      - name: chart-volume
        hostPath:
          path: /opt/ccp/charts/
          type: Directory
