apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ccp-istio-operator-role
rules:
- apiGroups:
  - operator.ccp.cisco.com
  resources:
  - istios
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - operator.ccp.cisco.com
  resources:
  - istios/status
  verbs:
  - get
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ccp-istio-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ccp-istio-operator-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
